### ISSUE TITLE
How to play two stream url (one video only, one audio only)

### ISSUE THREAD

**Issue by westlinkin** [protyposis/ITEC-MediaPlayer#1]
Hello. Great library!

I have two urls, one is video only and the other is audio only. I want to use the `MediaPlayer` to play these two urls to combine the video and audio, makes the two source sync with each other. Looks like it is playing from one url(which contains video and audio), How can I do that?

I found in your source code that, in [UriSource](https://github.com/protyposis/ITEC-MediaPlayer/blob/master/MediaPlayer/src/main/java/at/aau/itec/android/mediaplayer/UriSource.java) class, the `getAudioExtractor ()` method always returns null. Is it working like this:

``` java
@Override
    public MediaExtractor getVideoExtractor() throws IOException {
        MediaExtractor mediaExtractor = new MediaExtractor();
        mediaExtractor.setDataSource(mContext, mVideoOnlyUri, mHeaders);
        return mediaExtractor;
    }

    @Override
    public MediaExtractor getAudioExtractor() throws IOException {
         MediaExtractor mediaExtractor = new MediaExtractor();
        mediaExtractor.setDataSource(mContext, mAudioOnlyUri, mHeaders);
        return mediaExtractor;
    }

```

Of course, two `mUri`s are passed into this class.

Then, in your [MediaPlayer](https://github.com/protyposis/ITEC-MediaPlayer/blob/master/MediaPlayer/src/main/java/at/aau/itec/android/mediaplayer/MediaPlayer.java) class, set up your `mAudioExtractor`. Now in this part, I'm not quite understand your code. How to set up it?

Is it possible that `MediaPlayer` plays two stream urls?

**Comment by protyposis** [comment]
Hi Wesley! 

You were exactly on the right track, and there's actually nothing to set up in the `MediaPlayer` because it already supports separate sources for audio and video (it has already been implemented for DASH support). All that is to do is return an `AudioExtractor` from a `MediaSource` like in your code snippet.

I just commited updated `FileSource` and `UriSource` classes which now support separate audio and video sources (eb76875) and can confirm it working :)

Thank you for posting!

**Comment by westlinkin** [comment]
Thanks, it's working, but the audio isn't exactly sync with the video on some devices (like kindle fire hdx 7), it's working perfectly on Nexus 5(version 5.1). Could you please tell the reason why it's not syncing?

**Comment by protyposis** [comment]
It seems like A/V sync is a common problem on the Kindle Fire, even Netflix had it's issues there. The solution would probably be to hardcode the lag of problematic devices (or programmatically measure it on the fly) and adjust playback accordingly.

The `MediaPlayer` would need a `setAudioOffset(int offsetMs)` function to set the audio offset relatively to the video, which would internally work by either delaying the audio stream when the offset is negative or delaying the video stream when the offset is positive. I guess that's not going to be easily implemented though and would require rather big changes...

**Comment by westlinkin** [comment]
Thanks for this solution, I guess this is more of a hardware problem than a software problem. These devices are just not powerful enough. I'll try fix this as possible as I can.
