### ISSUE TITLE
Cannot play fragmented mp4 files

### ISSUE THREAD

**Issue by amoussawi** [protyposis/ITEC-MediaPlayer#10]
hello
I'm trying to play a fragmented mp4 file(using GPAC tool), and it's not playing, while it's playing normally on my pc? is it supported or not?

**Comment by protyposis** [comment]
Hi! Fragmented MP4 is supported for DASH streaming, but not for "normal" file playback. Normal file playback uses the MediaExtractor from the Android system which does not support fragmented MP4.

For DASH streaming, the fragments must either be split into separate files or specified through byte ranges in the MPD (reading of an index block from a file is not supported).

**Comment by amoussawi** [comment]
Thank you for your response! but as of android 4.3 (https://developer.android.com/about/versions/android-4.3.html#Multimedia) fragmented mp4 playback is supported or is it only for dash also?

**Comment by amoussawi** [comment]
I created an fragmented mp4 file using GPAC where the byte ranges are listed in the MPD, but audio and video tracks were not separated, when i tried to play DASH on ITEC, it didn't work and threw an exception, then i tried to separate audio and video tracks, where each has it's own adaptation set, it worked perfectly, but is there a way to do it without separating the audio and video tracks?

**Comment by protyposis** [comment]
That's interesting, I could not get my Nexus devices with Android 5.x to play back fragmented MP4 files and assumed it's not supported, so I used the mp4parser library to read the fragmented files for DASH playback. Ok so basically normal playback of fragmented files should work too, according to the docs.

Seems like I didn't think about the use case of multiplexed audio/video in a single adaptation set... I'll take a look into it tomorrow and see if it's possible to add support for this...

**Comment by amoussawi** [comment]
i tried playing fragmented mp4 using android videoview (android 4.4.4), but it didn’t work, it seems it is supported only for dash streaming.
please update me if you are able to add support for multiplexed audio/video.

**Comment by protyposis** [comment]
I created a multiplexed test DASH stream with mp4box and could play it back without an exception (which exception are you getting?). Unfortunately it only plays back the video stream though... the MediaExtractor does not pick up the audio stream for some reason, although both track definitions are in the init segment. I don't really have an idea on how to solve this except writing a custom extractor and ditching the Android MediaExtractor completely :/

**Comment by amoussawi** [comment]
i'm getting exception "couldn't find video track" in the mediaplayer because the videoformat is null, what options did use to create the multiplexed dash stream? what i wrote is 
"mp4box -frag 1000 -dash 1000 -profile (live or ondemand same result) file.mp4"
and also can i use a local MPD file for playback by just passing the URI of the local file to the DashSource, or it has to be in some server?

**Comment by protyposis** [comment]
I used the exact same command. Can you take a look at the indexes of the multiplexed streams (`mp4box -info dashfile.mp4`)? Maybe the audio track comes first in your file, so the MediaExtractor isn't picking up the video track (same problem as above with the missing audio)?

I never tried specifying local files for DASH, so I guess it might fail. The DashSource uses OkHttp to download the segments, so it depends on OkHttp if it can resolve and load local files. You'll have to give it a try.

**Comment by amoussawi** [comment]
yes the audio track comes before the video track, that's the problem!
i don't think okhttp load can load local files unless it's cached.

**Comment by protyposis** [comment]
Damn, so it's a limitation of the MediaExtractor that I can't do anything about...

Regarding local file support, I guess you'd like to use it because it's convenient for development? I think it does not make much sense to implement this functionality directly in the library, because it wouldn't be DASH (streaming over HTTP) any more. But you could install a local HTTP server app from the Play Store, specify the directory of the DASH files as root directory and access them through localhost urls.

**Comment by amoussawi** [comment]
yes it's more convenient for development....i'm going to install a local http server...actually if there's a way to get benefit from segmented mp4 file and MPD that would be awesome, but i guess dash is the only one that maintains it, and dash should not be limited to http, it has to be a standard that could be used in any case and not specific to http streaming. I need DASH in a very special case, so i have to modify a lot of things

**Comment by protyposis** [comment]
I just found the problem with the multiplexed streams! It's not the MediaExtractor's fault, but a problem in the DashMediaExtractor... I'm only reading the first track box there because I didn't consider multiplexed streams. Will push an update tomorrow...

**Comment by protyposis** [comment]
Fix is pushed in commit f2f39910, and it works for my test case. Can you double check if you multiplexed video is playing now?

**Comment by amoussawi** [comment]
Oh nice that's good... I will test it and inform you what i get....thanks a lot....it's awesome that you only had to change two lines of code :+1:

**Comment by amoussawi** [comment]
oh amazing it's working :100: :100:
thanks a lot :+1:

**Comment by godvmxi** [comment]
@abdallah95 　　did you test the fragemented mp4 on mediaplayer-extended ? how can I do it ?

**Comment by amoussawi** [comment]
it has been a year since I tested and I'm not using it anymore. I'm sorry I don't remember exactly how I did it. but I think I put a fragmented-mp4 in my local web server and streamed it to the device.

**Comment by protyposis** [comment]
You need to create a DASH MPD for the fragmented MP4 file and serve it over http.
