### ISSUE TITLE
Cannot get exact time(milliseconds) for duration and currentPosition

### ISSUE THREAD

**Issue by boris-dev** [protyposis/ITEC-MediaPlayer#104]
getCurrentPosition ()
getDuration()
in seconds, why?
I cannot use this lib, because I need milliseconds

**Comment by protyposis** [comment]
Both methods do return milliseconds.

**Comment by boris-dev** [comment]
Oh, really, thank you, May be threre is a way how to make getCurrentPosition update more often?
