### ISSUE TITLE
How to make getCurrentPosition() update more often

### ISSUE THREAD

**Issue by boris-dev** [protyposis/ITEC-MediaPlayer#105]
I need getCurrentPosition() return exact milliseconds, but it updated once in 100ms
How can I change it?
Thank you

**Comment by protyposis** [comment]
There is no limitation on how often `getCurrentPosition()` updates - it always returns the current time at every call. Your theory that it updates only every 100ms would only hold true if you play back a 10 fps video without audio.

**Comment by boris-dev** [comment]
@protyposis  I played midi files and I calculated that **loopInternal()**  calls 20 times a second, It means - every 50ms, 
For my app, I need to know exact ms of currentPosition, may be I can know time of last loopInternal call, and calculated it by myself?

**Comment by boris-dev** [comment]
Standart andorid MediaPlayer lib return exact currentPosition, but has a bug with playing some of my midi files, your library played them perfectly (I don't know why)
