### ISSUE TITLE
Reverse Playback

### ISSUE THREAD

**Issue by keremkusmezer** [protyposis/ITEC-MediaPlayer#107]
Hi,

We need a reverse playback solution implementation on the player for our video content and application purposes as well so setting the playback speed to a negative number , i know there are lots of the restrictions because of the way the video is compressed but on iOS that feature is implemented out of box and works decently i am trying to achieve the same implementation in Android , is there a way to do that with protyposis , i have some implementation on a exoplayer fork but it doesn't work very well

**Comment by protyposis** [comment]
As you already mentioned, video compression algorithms are designed for forward playback. While backward playback isn't impossible, it requires much more effort and resources for a very rare use-case so most video players do not implement it. It's not implemented in this library and I am also not aware of others that can do it nicely.
