### ISSUE TITLE
Can not play a mp4 file recorded by ios.

### ISSUE THREAD

**Issue by adawset** [protyposis/ITEC-MediaPlayer#11]
android.media.MediaPlayer does not work too.
But:
Only on my Nexus4(cm-12 system), both ITEC-MediaPlayer and android.media.MediaPlayer does work fine.

**Comment by protyposis** [comment]
The Android MediaPlayer and ITEC MediaPlayer use the same system codecs, so they exhibit the same behaviour. If a file is not supported by the system, it doesn't play back with either. The system codec implementations unfortunately depend on the vendor, and thus are not consistent across different Android devices (except for the minimum requirements: [core media formats](http://developer.android.com/guide/appendix/media-formats.html#core)).

Your iOS file is probably a QuickTime (.mov) container, which is a special kind of MP4 container, that is not part of the Android core media formats and therefore not supported by all devices.

If you want consistent behaviour for exotic file formats, you need to supply the codec with your app, e.g. by using FFmpeg.

Btw., this is related to issue #7.
