### ISSUE TITLE
Maven Central Migration 

### ISSUE THREAD

**Issue by ryanb-saltech** [protyposis/ITEC-MediaPlayer#120]
Since JCenter will no longer be receiving support and is deprecated in newer versions of gradle, can this be migrated over to MavenCentral? Thanks!

**Comment by protyposis** [comment]
Sorry, this is currently not scheduled to happen unless I publish a new version (which isn't planned either).

**Comment by ryanb-saltech** [comment]
Okay, thanks for the update.

**Comment by protyposis** [comment]
The library is now available on Maven Central starting with v4.5.0.
