### ISSUE TITLE
"net.protyposis.android.mediaplayer.VideoView" is not being recognized as a view

### ISSUE THREAD

**Issue by LeonelZalegas** [protyposis/ITEC-MediaPlayer#121]
I implemented the "implementation 'net.protyposis.android.mediaplayer:mediaplayer:4.5.0' " in the dependencies of my app build.gradle but is not working

**Comment by protyposis** [comment]
Hi, did the dependency download and install correctly? What is the exact error message in the Gradle build log?

**Comment by LeonelZalegas** [comment]
Hi ! Yes, the dependency did download and installed correctly, i didn't had any error or anything, is just that it does not recognize the "net.protyposis.android.mediaplayer.VideoView" view for some reason, in any case i just cloned the repo and imported it as a module directly into my project, and it works just fine now, so I guess the problem is just related to the implementation in the dependencies

**Comment by protyposis** [comment]
The dependency didn't download because I forgot to publish it in Maven Central :) You must have gotten a `Failed to resolve` error during Gradle sync.

Anyway, I just published it and now it works correctly.
