### ISSUE TITLE
dequeueOutputBuffer---- Does not support most of the equipment

### ISSUE THREAD

**Issue by mengzhidaren** [protyposis/ITEC-MediaPlayer#14]
mMediaCodec.dequeueOutputBuffer(info, kTimeOutUs);
这个语句经常返回-1，如果把延迟设为-1的话则又一直堵塞，为什么dequeueOutputBuffer会一直失败    很多真机都运行不了     例如: 三星S3

**Comment by protyposis** [comment]
Please post in English! Thank you.
