### ISSUE TITLE
Jcenter modules are not resolved

### ISSUE THREAD

**Issue by Dimezis** [protyposis/ITEC-MediaPlayer#17]
Jcenter modules are not resolved.
Tried 
`compile 'net.protyposis.android.mediaplayer:mediaplayer:3.0.0'`
and
`compile 'net.protyposis.android.mediaplayer:mediaplayer:2.2.3'`

**Comment by protyposis** [comment]
Thank you for reporting!

The package name has been changed for v3.0.0 and JCenter seems to have issues with that. I have asked their support for help.

In the meantime, please use v2.2.3 with the old package name:
`compile 'at.aau.itec.android.mediaplayer:mediaplayer:2.2.3'`

**Comment by protyposis** [comment]
Issue resolved. Modules of v3 are now available in JCenter and the readme has been updated accordingly, thus this is now working:
`compile 'net.protyposis.android.mediaplayer:mediaplayer:3.0.0'`

Thanks again for reporting!

**Comment by Dimezis** [comment]
Thank you
