### ISSUE TITLE
ITEC MediaPlayer doesn't build on jitpack.io

### ISSUE THREAD

**Issue by PaulWoitaschek** [protyposis/ITEC-MediaPlayer#2]
Unfortunately does not build. Would really like to use this since neither ExoPlayer nor MediaPlayer are able to set playback speed.

See https://github.com/jitpack/jitpack.io/issues/91#issuecomment-108834329

**Comment by jitpack-io** [comment]
Appears to be a lint issue

**Comment by protyposis** [comment]
Fixed in d18a75dd4 (release v1.3.1).

Btw., you don't need to include the MediaPlayer-DASH dependency (which caused the problem) for ordinary video file playback.

**Comment by protyposis** [comment]
The library is now available in the JCenter Maven repository, see `README` for details.

**Comment by kotya341** [comment]
Thanks for your help . Can you please say when I can get this changes in release instead of using fork
