### ISSUE TITLE
WMV,FLV not support

### ISSUE THREAD

**Issue by uttanshts** [protyposis/ITEC-MediaPlayer#22]
MediaPlayer-Extended not support .wmv and .flv format video only sound play no video.

**Comment by protyposis** [comment]
This is expected as Android does not support these formats: [Android media formats](https://developer.android.com/guide/appendix/media-formats.html)

**Comment by uttanshts** [comment]
But These file play properly in normal default video player.

**Comment by protyposis** [comment]
What happens when you ty to play such a file? Any exception in logcat?

Edit: 
I checked it on two phones:
Nexus 5X: unsupported formats, exceptions thrown
Galaxy A3 2016: WMV plays, FLV unsupported format, exception thrown

If they play in the default player, then maybe its just a bug preventing playback. Please post the exceptions from logcat.

**Comment by uttanshts** [comment]
only play sound

08-22 16:30:09.925: I/dalvikvm(29710): Could not find method android.media.MediaCodec.releaseOutputBuffer, referenced from method net.protyposis.android.mediaplayer.MediaCodecVideoDecoder.releaseFrame
08-22 16:30:09.925: W/dalvikvm(29710): VFY: unable to resolve virtual method 633: Landroid/media/MediaCodec;.releaseOutputBuffer (IJ)V
08-22 16:30:09.925: D/dalvikvm(29710): VFY: replacing opcode 0x6e at 0x000f
08-22 16:30:09.925: I/Utils(29710): Receiving the message for 'kKeyCodecConfig'.
08-22 16:30:09.925: I/ACodec(29710):  [] Now uninitialized
08-22 16:30:09.925: I/OMXClient(29710): Using client-side OMX mux.
08-22 16:30:09.935: I/ACodec(29710): [OMX.SEC.wmv8.dec] Now Loaded
08-22 16:30:09.935: I/Utils(29710): Receiving the message for 'kKeyCodecConfig'.
08-22 16:30:09.935: E/ACodec(29710): [OMX.SEC.wmv8.dec] storeMetaDataInBuffers failed w/ err -2147483648
08-22 16:30:09.935: I/ACodec(29710): DRC Mode: Port Reconfig Mode
08-22 16:30:09.935: I/ACodec(29710): [OMX.SEC.wmv8.dec] Now Loaded->Idle
08-22 16:30:09.955: I/ACodec(29710): [OMX.SEC.wmv8.dec] Now Idle->Executing
08-22 16:30:09.955: I/ACodec(29710): [OMX.SEC.wmv8.dec] Now Executing
08-22 16:30:09.955: D/MediaCodecVideoDecoder(29710): reinitCodec 21ms
08-22 16:30:09.955: I/Utils(29710): Receiving the message for 'kKeyCodecConfig'.
08-22 16:30:09.955: I/ACodec(29710):  [] Now uninitialized
08-22 16:30:09.955: I/OMXClient(29710): Using client-side OMX mux.
08-22 16:30:09.955: I/ACodec(29710): [OMX.SEC.wma.dec] Now Loaded
08-22 16:30:09.955: I/Utils(29710): Receiving the message for 'kKeyCodecConfig'.
08-22 16:30:09.965: D/AudioPlayback(29710): init
08-22 16:30:09.965: I/ACodec(29710): [OMX.SEC.wma.dec] Now Loaded->Idle
08-22 16:30:09.975: D/MediaCodecAudioDecoder(29710): reinitCodec 17ms
08-22 16:30:09.975: I/ACodec(29710): [OMX.SEC.wma.dec] Now Idle->Executing
08-22 16:30:09.975: I/ACodec(29710): [OMX.SEC.wma.dec] Now Executing
08-22 16:30:10.005: D/MediaPlayer(29710): onVideoSizeChanged
08-22 16:30:10.015: D/MediaCodecVideoDecoder(29710): output format has changed to {height=480, what=1869968451, color-format=19, slice-height=480, crop-left=0, width=640, crop-bottom=479, crop-top=0, mime=video/raw, stride=640, crop-right=639}
08-22 16:30:10.015: D/MediaCodecAudioDecoder(29710): output format has changed to {sample-rate=44100, channel-count=2, what=1869968451, mime=audio/raw}
08-22 16:30:10.015: D/AudioPlayback(29710): incoming frame chunk size increased to 8192
08-22 16:30:10.015: D/AudioPlayback(29710): init
08-22 16:30:10.015: D/AudioPlayback(29710): incoming frame chunk size increased to 10240
08-22 16:30:10.015: D/AudioPlayback(29710): init
08-22 16:30:10.025: D/MediaCodecVideoDecoder(29710): seeking to:                 0
08-22 16:30:10.025: D/MediaCodecVideoDecoder(29710): extractor current position: 400000
08-22 16:30:10.035: D/MediaCodecVideoDecoder(29710): extractor new position:     0
08-22 16:30:10.035: I/ACodec(29710): [OMX.SEC.wmv8.dec] Now Flushing
08-22 16:30:10.035: I/ACodec(29710): [OMX.SEC.wmv8.dec] Now Executing
08-22 16:30:10.065: I/ACodec(29710): [OMX.SEC.wma.dec] Now Flushing
08-22 16:30:10.065: I/ACodec(29710): [OMX.SEC.wma.dec] Now Executing
08-22 16:30:10.065: D/MediaPlayer(29710): onPrepared
08-22 16:30:10.065: D/MediaPlayer(29710): seekTo 0
08-22 16:30:10.065: D/VideoViewActivity(29710): onSeek
08-22 16:30:10.065: D/MediaCodecVideoDecoder(29710): seeking to:                 0
08-22 16:30:10.065: D/MediaCodecVideoDecoder(29710): extractor current position: 400000
08-22 16:30:10.075: D/MediaCodecVideoDecoder(29710): extractor new position:     0
08-22 16:30:10.075: I/ACodec(29710): [OMX.SEC.wmv8.dec] Now Flushing
08-22 16:30:10.075: I/ACodec(29710): [OMX.SEC.wmv8.dec] Now Executing
08-22 16:30:10.085: D/MediaCodecVideoDecoder(29710): frame new position:         0
08-22 16:30:10.085: D/MediaCodecVideoDecoder(29710): seeking finished, skipped 0 frames
08-22 16:30:10.085: D/MediaCodecVideoDecoder(29710): exact seek match!
08-22 16:30:10.085: I/ACodec(29710): [OMX.SEC.wma.dec] Now Flushing
08-22 16:30:10.095: I/ACodec(29710): [OMX.SEC.wma.dec] Now Executing
08-22 16:30:10.095: D/MediaPlayer(29710): onSeekComplete
08-22 16:30:10.095: D/VideoViewActivity(29710): onSeekComplete
