### ISSUE TITLE
4x fast

### ISSUE THREAD

**Issue by uttanshts** [protyposis/ITEC-MediaPlayer#23]
S3 camera  video not play in normal speed if I use 4x speed. only sound is play in 4x speed

other video like 3gp, and mp4 song play properly with 4x speed

**Comment by protyposis** [comment]
A video is not playing in normal speed when you use 4x speed? Are you talking about slow motion video?

Anyway, if playback is too slow, then the CPU/GPU of the device is too slow and cannot decode the video fast enough. This will vary by format and resolution (e.g. lower resolution of course decodes faster).

That the audio is playing too fast when video decoding cannot keep up is an AV sync issue and needs to be fixed though.

**Comment by uttanshts** [comment]
I am talking about 4x fast sound is play in 4x fast speed but video is in same(normal speed)

Video capture from camera(S3)
Orientation Portrait
Duration 10min
size 1.22Gb

**Comment by protyposis** [comment]
Can you upload such a video clip?

**Comment by uttanshts** [comment]
it is too  large

**Comment by protyposis** [comment]
Record a short clip or use Dropbox, Google Drive, OneDrive, Mega, Wetransfer, ...

**Comment by uttanshts** [comment]
Pl.share your id

**Comment by protyposis** [comment]
Which id? I'm sorry but this is tiring. If you want me to spend my spare time to help you, get more cooperative and show some initiative.
