### ISSUE TITLE
[VideoView] onCompletion issue

### ISSUE THREAD

**Issue by ghost** [protyposis/ITEC-MediaPlayer#26]
When onCompletion occurs, the current position and duration are not same
I have attached debug image
![debug](https://cloud.githubusercontent.com/assets/13575382/19182226/5707a4e6-8c9c-11e6-8176-5f78f1395c2b.png)

**Comment by protyposis** [comment]
You cannot rely on duration and end position being the same. The duration is just some metadata in the video file and must not necessarily match the playback duration, which is derived from the actual video frames. You can work around that though: in onCompletion, update the duration with the end position, or set the position to the duration value.

Btw., you have to add an open source credits screen to your app. You are violating the license of this and many other open source libraries.
