### ISSUE TITLE
Buffering progress never updated

### ISSUE THREAD

**Issue by aleksandra-majchrzak** [protyposis/ITEC-MediaPlayer#29]
I noticed that when playing online video secondary bar on MediaController (the one which indicates buffering progress) never gets updated- the same code with standard MediaPlayer worked fine. Here mediaPlayer's method onBufferingUpdate() never gets called. I found out that it is called when there is MEDIA_BUFFERING_UPDATE message send. And it is send in loopInternal() method when cachedDuration is not equal -1. I dug into method mDecoders.getCachedDuration() and I think that as minCachedDuration is initialized with -1 we will never get positive value from this method therefore bufferPercentage never gets updated.

Please, confirm if my observations are correct and if so, make some changes in getCachedDuration() method.

**Comment by protyposis** [comment]
Thanks for reporting this bug. As you commanded, my master, I have fixed this error in version 4.0.2.
