### ISSUE TITLE
Video playback speed

### ISSUE THREAD

**Issue by scerelli** [protyposis/ITEC-MediaPlayer#33]
Hi @protyposis thanks for the work you did with this package.

I made a bridge for `react-native`using your package, you can see it here: https://github.com/scerelli/react-native-android-video-player

Everything works smooth except for the playback speed. If i set it under `1.0` the video run slower as expected but it lags a little bit. There is a way to avoid this behaviour?

**Comment by protyposis** [comment]
Hi, thanks for using the library! What do you mean with "it lags"? Do you mean the playback speed is unsteady and fluctuating?

**Comment by scerelli** [comment]
yes ;)

**Comment by protyposis** [comment]
Alright, thanks for reporting. That is definitely a bug that needs to be fixed.

**Comment by scerelli** [comment]
it has the same problem even if you set `-1.0`. It should play the video reversed doesn't it?

**Comment by protyposis** [comment]
Reverse playback is not possible, the next version will throw an exception when a negative number is set. 

Video codecs are designed for forward playback, that's why video players don't offer this feature...  it could be implemented, but it'd be extremely costly.

**Comment by protyposis** [comment]
Should be fixed now. Please let me know if it works!
