### ISSUE TITLE
setAudioStreamType not accessible

### ISSUE THREAD

**Issue by lucas34** [protyposis/ITEC-MediaPlayer#39]
Hi,

Your library does not allow me to choose if I want to play by using the music speaker or the phone call speaker. The setAudioStreamType() for media player is not accessible. 

Is there any specific reason to hide this capability ?

**Comment by protyposis** [comment]
Hey, no specific reason, except nobody has needed it yet :) That's pretty easy to implement so it'll be part of the next release.
