### ISSUE TITLE
Early playback finish

### ISSUE THREAD

**Issue by xylik** [protyposis/ITEC-MediaPlayer#40]
Hi, am playing local mp4 files and player stops playing video 150-200ms before end(last frame in mp4 file) and does that consistently on different mp4 files. Early stop time is not fixed and varies around 150ms before video end, also before play finishes I've noticed small video stuttering.

Issue produced on Google Nexus 5(Lolipop 6.0.1), Samsung mini s4(Kitkta 4.4.2)

Link to video file:
https://drive.google.com/open?id=0Byn0xtAvVbCWZjIyaHlyNHBuYTA

**Comment by protyposis** [comment]
Thanks, I've been trying to fix this a few times already but never got it to work nicely. This time I think it's done.
