### ISSUE TITLE
Audio start lags behind video start

### ISSUE THREAD

**Issue by xylik** [protyposis/ITEC-MediaPlayer#42]
Hi, am playing local mp4 files but before play i always Precise seek to some position in video -typically non-keyframe and after seek i start playing the video. The problem am facing is that audio start lags behind the video start for cca 100ms(few frames). 

Issue produced on Google Nexus 5(Lolipop 6.0.1)

**Comment by protyposis** [comment]
Does the audio just start later but then plays back in sync with the video, or does it constantly lag behind?

**Comment by xylik** [comment]
Audio starts later but than they play in sync with video.

**Comment by protyposis** [comment]
That's an artifact from how the video file is muxed. In your case you're seeking to a position in the file where there's a few video frames without audio data in between, resulting in audio starting later. Depending on the muxer settings, this can get noticeable in extreme cases.

But is that really an issue? Most people would probably not notice that if it's just 100ms.

**Comment by xylik** [comment]
I will do some benchmark over the weekend and give you feedback with exact numbers because I haven't spend enough time with that problem. The guy that noticed it says it's consistent and noticeable.

**Comment by xylik** [comment]
I would say for now that's not really the issue because is hardly noticeable, you can close the issue.

**Comment by protyposis** [comment]
Ok, thank you!
