### ISSUE TITLE
Can not change surface while playing the video?

### ISSUE THREAD

**Issue by futurexiong** [protyposis/ITEC-MediaPlayer#44]
I want to set another surface to mediaplayer while playing the video, so that I can easily switch the mediaplayer between normal mode and fullscreen mode. I have read part of the source code, seens this feature is not yet support. Any schedule on it?

**Comment by protyposis** [comment]
Hi, changing the surface works, just call `setDisplay` or `setSurface`. You will get video compression artifacts when changing the surface because the codec will be recreated and reference frames get lost. The cleaner way would be using the same surface for windowed and fullscreen mode and changing the layout.

**Comment by futurexiong** [comment]
When I remove the textureview from it's parent and add it into another fullscreen view, the first surfacetexture will be destroyed before the second surfacetexture available. So before I can call setSurface to set another surface to the mediaplayer in the onSurfaceTextureAvailable method, the mediaplayer will run into onError since the first surfacetexture is destroyed. The decode and render process will throw IllegalStateException.

**Comment by protyposis** [comment]
In this case you need to pause playback while doing that to avoid the player rendering to an invalid surface. But removing and re-adding the surface from/to the layout is almost the same as working with two surfaces, just more complicated.

To use the same surface for windowed and fullscreen modes, you shouldn't remove it from the layout, just resize it.

**Comment by futurexiong** [comment]
Pause playback doesn't work, because we call pause() on main thread while decode and render are on the playbackthread. Resize the surface always works but in some situation I can't just resize it. For example I use the parent layout in a list, but that list can't be resize to fullscreen.
