### ISSUE TITLE
PlaybackThread memory leak

### ISSUE THREAD

**Issue by piotrmadry** [protyposis/ITEC-MediaPlayer#45]
Hello, I've just figured out that somehow PlaybackThread holding instance of Media Player because of `mOnBufferingListener`. 
I'm sure that this listener is null before close Activity where it is registered.
Maybe I'm missing something.. Can you take a look at this ?

**Comment by protyposis** [comment]
Hi! The PlaybackThread doesn't reference `mOnBufferingUpdateListener` anywhere, but even if it would, I can't imagine how it could leak the MediaPlayer. If you `setOnBufferingUpdateListener` in an activity and close the activity, you also don't need to set it to `null` before closing. Just make sure to call `release()` on the MediaPlayer.

If you're sure there is a leak, I'm happy to take a deeper look, but I'll need more detailed information on how to reproduce or observe the issue.

**Comment by protyposis** [comment]
Can you please try 4.2.2-rc1 and see if it fixes your issue?

**Comment by piotrmadry** [comment]
I saw your explanation. Thanks for it. Gonna test it now

**Comment by piotrmadry** [comment]
Actually it works perfectly. Thanks for fix. I'm closing it!

**Comment by protyposis** [comment]
Great, thank you!
