### ISSUE TITLE
Hardware accel

### ISSUE THREAD

**Issue by ihostbert** [protyposis/ITEC-MediaPlayer#47]
Hi there. I'm new to android video and was having some issues with the native videoview I used your replacement and love it. I was curious if you wereinstall planning on taking advantage of hardware accel if possible or even releasing a version that can work with exoplayer 

Like I said I am new so apologies in advance if I'm not asking or understanding. ..

Either way great work on the lib

**Comment by protyposis** [comment]
Hi, thank you! This player uses the same system components to decode video that the native player and ExoPlayer use, and automatically takes advantage of hardware acceleration (hardware decoding) on devices that support it. 
Hope that answers your question!
