### ISSUE TITLE
I can't set a zoom level 

### ISSUE THREAD

**Issue by kotya341** [protyposis/ITEC-MediaPlayer#5]
As I understand your code , all my zoom level params are not chaning a real level of zoom 
Can you please check it ?
https://github.com/protyposis/ITEC-MediaPlayer/blob/master/MediaPlayer-GLES/src/main/java/at/aau/itec/android/mediaplayer/GLTextureView.java#L161

**Comment by protyposis** [comment]
Hi, thanks for reporting! That was a stupid bug, it is fixed in 4b20771.

**Comment by protyposis** [comment]
Btw, setting zoom and pan only works after the player is prepared for playback, i.e. after the 'OnPreparedListener' has been called.

**Comment by kotya341** [comment]
Thanks for your help . Can you please say when I can get this changes in release instead of using fork

**Comment by protyposis** [comment]
Version 1.3.3 is now on jCenter!
