### ISSUE TITLE
Audio only ?

### ISSUE THREAD

**Issue by qstuff** [protyposis/ITEC-MediaPlayer#52]
Is there an easy way to play audio files, only ?

**Comment by qstuff** [comment]
I got it working :) was some minor hacking in your code. if you want i can sent you a diff or open an PR

**Comment by protyposis** [comment]
Hi Claus! That should actually work out-of-the-box by just specifying the path to an audio instead of a video file. I just tested it on the latest version. Which change did you have to make?

**Comment by qstuff** [comment]
You're right. Just double checked it. The issue was in my code. While debugging i made some changes in your code and first assumed that this fixed my problems. So i will close the issue.
Anyway: Good work. I was searching a while for a player solution that allows me setting the playback speed and works also on API level < 23 for a private player project. Now i got it :)
Thank you
