### ISSUE TITLE
Rotate Issue

### ISSUE THREAD

**Issue by KungFuArsong** [protyposis/ITEC-MediaPlayer#54]
The video doesn't rotate on Android Version 4.2.2, 4.3.2.
I just changed the MediaFromat rotation-degrees and rotation value
but the video doesn't chagne yet

**Comment by protyposis** [comment]
Video rotation is only supported from Android 5.0. See #6. Also, setting the rotation manually won't work, as this is a read-only value.

**Comment by KungFuArsong** [comment]
this source used surfaceview,
but if you use textureview, you can rotate the video
I tried to use textureview on this source code, but I failed.
my idea is right or not?

**Comment by protyposis** [comment]
Yes you can use `TextureView` instead of `SurfaceView` with the `MediaPlayer` to rotate the video, if you know the rotation value. Android below 5.0 won't report the rotation in `MediaFormat`.

**Comment by KungFuArsong** [comment]
I wrote issue because I couldn't fix this issue.
if you can fix this rotate issue, I hope you help me
I will pay for that

**Comment by protyposis** [comment]
For paid support, please get in contact through support@protyposis.com. Thank you!
