### ISSUE TITLE
Fast switching video source issue

### ISSUE THREAD

**Issue by piotrmadry** [protyposis/ITEC-MediaPlayer#55]
Hello! 
I have problem when I'm trying to set video source one after another to the same VideoView.
Basically I'm getting `IllegalStateException` at `prepareAsync()` It when I'm setting many different video sources one by one (Monkey tests) 

I want to add that before I set new source I'm doing `videoView.stopPlayback()`
How to avoid this issue ? Or maybe it is fixable ?

Thanks for fast answer.
Regards

**Comment by protyposis** [comment]
Hi, I cannot reproduce this issue. Can you please post some sample code to reproduce?

**Comment by protyposis** [comment]
Since I haven't heard from you, I'm closing this for now. Feel free to reopen anytime.

**Comment by vishalkumarsinghvi** [comment]
help me with same issue
