### ISSUE TITLE
Frame accuracy issues on videos when Ctts.SampleOffset is not zero

### ISSUE THREAD

**Issue by apwillies** [protyposis/ITEC-MediaPlayer#57]
[UPDATED to eliminate reference to B-frames - these videos start with an I-frame]

When a video has a Ctts.SampleOffset that is not zero, frame accuracy is off by the specified time offset. 

**Prerequisites:**
This happens only on **Android 5 and later**. In other words, the issue is not observed on KitKat and Jelly Bean (4.1.x to 4.4.x). We also see no difference in behavior based on device manufacturer.

**Sample Videos:** These have a SampleOffset of 0.0667333, equivalent to 2 frames
1. [Joshua 1, 720p](https://download-a.akamaihd.net/files/media_bible/5e/nwt_06_Jos_ASL_01_r720P.m4v) At frame 400 / time code 13363 milliseconds, the on screen text should display "Joshua 1:5". Because it is displaying 2 frames early, it still displays "Joshua 1:2".
2. [Joshua 23, 480p](https://download-a.akamaihd.net/files/media_bible/65/nwt_06_Jos_ASL_23_r480P.m4v) At frame 1846 / time code 33750 milliseconds, the on screen text should display "Joshua 23:14". Because it is displaying 2 frames early, it still displays "Joshua 23:6".

The videos were created using FFMPEG and are composed of several clips from other files that are stitched together to form a new files. [I can provide further information on the exact command used, if needed.]

**Notes:**
Videos that have a SampleOffset are common in the last few years as the MP4 standard has evolved. It is hard to nail down the problem, but we used several tools to help diagnose the difference between files that work fine and files that are off by a couple of frames. 

[AVIDemux](https://www.fosshub.com/Avidemux.html) shows that the video opens with the Time already set to 00:00:00.066. This indicates that the "zero" position is actually 2 frames into the video.

**Comment by protyposis** [comment]
Thanks for the report, this should be easily fixable. Will look into it in the coming days.

**Comment by apwillies** [comment]
Thanks for the response! Will be looking out for the update.

**Comment by apwillies** [comment]
@protyposis We just made a build that includes this fix and it solves our issue. Thanks for taking the time! 

Will you be including this in a future 4.2.3 release? Or do you have another release path planned?

**Comment by protyposis** [comment]
Yes this will be part of 4.2.3.

**Comment by protyposis** [comment]
`v4.3.0` is out :)
