### ISSUE TITLE
RTSP protocol

### ISSUE THREAD

**Issue by hsunwei423** [protyposis/ITEC-MediaPlayer#59]
hello, could this project support RTSP protocol?

I tried some RTSP uris but  it can't work.

**Comment by protyposis** [comment]
RTSP is a [supported network protocol](https://developer.android.com/guide/topics/media/media-formats.html) so it *should* work. Are you sure the stream uses supported codecs? Can you provide a test URI?

**Comment by hsunwei423** [comment]
I tried to test my onvif device but it didn't work. URI is like rtsp://[username]:[password]@192.168.x.x:554/... , would you tell me what's happened?

**Comment by protyposis** [comment]
I'm sorry but that is obviously not an URI I can test.

**Comment by hsunwei423** [comment]
Hello, I think I found a solution which I tried to do Basic Authentication with header but I don't know how to add header in your code. Would you tell me how to do this?
http://cruxintw.blogspot.tw/2015/03/android-mediaplayer-rtsp-streaming.html

**Comment by protyposis** [comment]
You can use one of these methods and supply the headers as a map:

* `MediaPlayer#setDataSource(new UriSource(Context context, Uri uri, Map<String, String> headers))`
* `MediaPlayer#setDataSource(Context context, Uri uri, Map<String, String> headers)`
* `VideoView#setVideoSource(new UriSource(Context context, Uri uri, Map<String, String> headers))`
* `VideoView#setVideoURI(Uri uri, Map<String, String> headers)`
