### ISSUE TITLE
Fast switching video source issue

### ISSUE THREAD

**Issue by vishalkumarsinghvi** [protyposis/ITEC-MediaPlayer#61]
same as issue 55 problem

**Comment by protyposis** [comment]
Duplicate of #55.

**Comment by vishalkumarsinghvi** [comment]
it's not working please reopen issue

**Comment by vishalkumarsinghvi** [comment]
Exception java.lang.IllegalStateException:
net.protyposis.android.mediaplayer.MediaPlayer.prepareAsync (MediaPlayer.java:466)
net.protyposis.android.mediaplayer.VideoView$2.run (VideoView.java:210)
java.lang.Thread.run (Thread.java:818)
