### ISSUE TITLE
Crash on 4.4 android

### ISSUE THREAD

**Issue by af-kabramov** [protyposis/ITEC-MediaPlayer#63]
```
D/MediaCodecAudioDecoder: output buffers have changed.
D/MediaCodecAudioDecoder: output format has changed to {sample-rate=48000, channel-count=2, what=1869968451, mime=audio/raw}
D/AudioPlayback: init
I/ACodec: [OMX.SEC.avc.dec] Now handling output port settings change
E/ACodec: ## 3d, eNativeColorFormat 0x15
E/ACodec: ## 3d, eNativeColorFormat 0x105
I/ACodec: [OMX.SEC.avc.dec] Allocating 6 buffers from a native window of size 4136960 on output port
I/ACodec: [OMX.SEC.avc.dec] Now Executing
D/MediaCodecVideoDecoder: output buffers have changed.
D/dalvikvm: GC_FOR_ALLOC freed 3032K, 30% free 9731K/13736K, paused 27ms, total 27ms
D/MediaCodecAudioDecoder: EOS input
D/MediaCodecVideoDecoder: EOS input
A/ACodec: frameworks/av/media/libstagefright/ACodec.cpp:2899 CHECK_LE( rect.nLeft + rect.nWidth - 1,videoDef->nFrameWidth) failed: 4294967295 vs. 0
A/libc: Fatal signal 6 (SIGABRT) at 0x000028a1 (code=-6), thread 10457 (CodecLooper)
D/MediaCodecAudioDecoder: EOS output
```

Crashes app on Android 4.4 when start playing video

**Comment by protyposis** [comment]
What type of file are you trying to play? Which container format, which kinds of tracks does it contain? Can you provide a sample file?

**Comment by af-kabramov** [comment]
splash.mp4
![image](https://cloud.githubusercontent.com/assets/9871300/25520715/9c41c326-2c05-11e7-90f2-a5c341d42e4e.png)
big resolution video and i think it is the reason, because on smaller videos it is good, but... it would be better not to crash app, just throw an exception =)

**Comment by protyposis** [comment]
Unfortunately I don't have a device to reproduce the error. On my Galaxy S2 with Android 4.1.2 playback of high-res videos (e.g. 4K) does not work (throws exception), but it does not crash.

**Comment by ashishvirani** [comment]
`java.lang.IllegalStateException
  at android.media.MediaPlayer.prepareAsync(Native Method)`

Crashes app on Android 5.1 when prepareMedia file

**Comment by protyposis** [comment]
@ashishvirani this is an unrelated exception, please open a separate issue and attach the whole stack trace. Thank you!
