### ISSUE TITLE
RTSP startup latency?

### ISSUE THREAD

**Issue by antucg** [protyposis/ITEC-MediaPlayer#65]
Hello I am developing a streaming application. I have used different libs to try to reproduce rtsp urls. They all work, but they all have some bug. I have a question for this one, the default MediaPlayer from Android has a big latency, so whenever I start reproducing some content it takes a few seconds to appear in the phone (10 seconds). With the sdk from VLC, the latency is between 1 and 2 seconds (ok for me). Would anybody be able to tell me if this is happening with this lib?

Thanks.

**Comment by protyposis** [comment]
Can't help you with an answer as I have never tried RTSP streams, but I set a more meaningful title for this question.

**Comment by antucg** [comment]
Thanks, I don't think that problem lies on the protocol, but the decoder. MediaPlayer base android class takes a lot of time to decode the stream. In the other hand VLC is much faster. Have you tried any other format of streaming? Was it ok?

**Comment by protyposis** [comment]
Progressive MP4 and DASH streaming is working fine, definitely no 10 sec startup. You can try the [demo](https://play.google.com/store/apps/details?id=at.aau.itec.android.mediaplayerdemo) and load your RTSP URL there to give it a try.

**Comment by antucg** [comment]
In that demo app when I paste a demo rtsp it says it can't load. Is it because rtsp is not supported or is it that demo only supports DASH?

**Comment by protyposis** [comment]
I'm sorry, it seems that for some reason the Android MediaExtractor does not support RTSP :(

**Comment by antucg** [comment]
Ok, thanks. Would you know any other alternative that might have support for rtsp?
Thanks.

**Comment by protyposis** [comment]
I'm afraid I don't know any alternative :(
