### ISSUE TITLE
Library missing from JCenter

### ISSUE THREAD

**Issue by praveenshharma** [protyposis/ITEC-MediaPlayer#69]
Hi, when I'm compiling this library into my gradle system its showing error like this..
Error:(84, 13) Failed to resolve: net.protyposis.android.mediaplayer:mediaplayer:4.3.0

Compilation way :-
compile 'net.protyposis.android.mediaplayer:mediaplayer:4.3.0'

I have tried all the things with Android Studio Settings, like (UTF-8 Encoding), but unable to build my gradle system

**Comment by protyposis** [comment]
Thanks for reporting! The package has disappeared from JCenter again. I don't know why this repeatedly happens, but I have asked to re-add it and it will be back in the next few days.

**Comment by protyposis** [comment]
It's back (much faster that usually) :) Please check if your issue is solved.

**Comment by oseparovic** [comment]
Maybe worth contacting JCenter to find out what's happening? There's a contact link at the bottom of their homepage https://bintray.com/bintray/jcenter

**Comment by protyposis** [comment]
Thanks, I'm already in contact with them and hope we can resolve that.

**Comment by protyposis** [comment]
Support told me that they have identified an issue and fixed it. We'll see :)

Closing this now.

**Comment by protyposis** [comment]
Been in contact with support for some time, they regularly find "issues" that they "fix", but the library keeps disappearing from JCenter every time I release a new version.

Currently it's gone again.

**Comment by protyposis** [comment]
Back online.
