### ISSUE TITLE
Mediaplayer Glitch on application switch

### ISSUE THREAD

**Issue by sanatyanky1988** [protyposis/ITEC-MediaPlayer#74]
when app switches while playing media player audio track. playback got silent for a short while sounds like  a audio pop

**Comment by protyposis** [comment]
Can you please describe more clearly? What exactly do you mean by "app switch"? Switching to another app and keeping the media player playing in the background?

**Comment by sanatyanky1988** [comment]
Yes, Switching to another app and keeping the media player playing in the background makes glitch (pause of few milliseconds)

**Comment by protyposis** [comment]
This probably depends on the performance of the device. Cannot reproduce on my test devices.
