### ISSUE TITLE
mediaplayer pause for a while on seekto when audio is playing

### ISSUE THREAD

**Issue by sanatyanky1988** [protyposis/ITEC-MediaPlayer#75]
i played a audio and seek to some seconds. when we seek again programatically audio pause for some time and playback starts

**Comment by protyposis** [comment]
How long is the pause? (a short pause is expected on a seek) Which audio format does it happen with?

**Comment by sanatyanky1988** [comment]
aac format and its 200 to 300 milliseconds

**Comment by protyposis** [comment]
You can try setting `mediaPlayer.setSeekMode(MediaPlayer.SeekMode.FAST_TO_CLOSEST_SYNC)`. That usually makes a different for video, but maybe not for audio. You'll have to try. If it doesn't help, there is nothing that I can do, as the seek is carried out by Android's MediaExtractor.
