### ISSUE TITLE
play rtsp streamer

### ISSUE THREAD

**Issue by andreabonassi** [protyposis/ITEC-MediaPlayer#76]
Good morning, 
can you help to play an rtsp stream?

**Comment by protyposis** [comment]
The Android system does not supports RTSP natively, so this is unfortunately not possible. #65.

**Comment by andreabonassi** [comment]
But if I userd Android VideoView rtsp work.
I would use our mediaplayer because VideoView StopPlayback() is very slow and get ANR.
