### ISSUE TITLE
Build fail with an Exception

### ISSUE THREAD

**Issue by jrgajera** [protyposis/ITEC-MediaPlayer#78]
Error:FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Android1\Downloads\Test Apps\11-11-2017\MediaPlayer-Extended-master\gitversioning.gradle' line: 14

* What went wrong:
Execution failed for task ':MediaPlayerDemo:processDebugManifest'.
> git not found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by protyposis** [comment]
Thanks for reporting. This error is expected though because the version string is created with `git` which seems not to be installed or available in your environment. You should install Git and clone the repository with Git then to get it to work correctly.
