### ISSUE TITLE
public void onBufferingUpdate(MediaPlayer mp, int percent) percent not correct

### ISSUE THREAD

**Issue by taosimple** [protyposis/ITEC-MediaPlayer#80]
`onBufferingUpdate(MediaPlayer mp, int percent)` percent value , sometimes roll back , and maybe beyond 100% , It's behavior  is strange.

**Comment by protyposis** [comment]
Thanks for reporting. This probably happens because the time offset between the extractor and the decoder is not taken into account for the buffer calculation. Will try to fix with the next release.

**Comment by protyposis** [comment]
This has been improved in 4.3.3. It can still roll back but that's how it's reported by the Android system.
