### ISSUE TITLE
Crash with "Failed to instantiate extractor" on 4.1.1

### ISSUE THREAD

**Issue by velocitysystems** [protyposis/ITEC-MediaPlayer#82]
Samsung GT-P3113 Android 4.1.1.
Crashes when attempting to play an MP4 video file. 
**Same player code used on 4.2 and up, and works fine on all other OS versions.**

```
	Caused by: java.io.IOException: Failed to instantiate extractor.
	at android.media.MediaExtractor.setDataSource(Native Method)
	at android.media.MediaExtractor.setDataSource(MediaExtractor.java:148)
	at net.protyposis.android.mediaplayer.MediaExtractor.setDataSource(MediaExtractor.java:121)
	at net.protyposis.android.mediaplayer.FileSource.getVideoExtractor(FileSource.java:60)
	at net.protyposis.android.mediaplayer.MediaPlayer.setDataSource(MediaPlayer.java:237)
	at net.protyposis.android.mediaplayer.MediaPlayer.setDataSource(MediaPlayer.java:318)
```

Usage is passing in a `Protyposis.MediaPlayerExtended.FileSource` to the `SetDataSource` method.
Could this potentially be a problem with Android 4.1.1 or a MediaPlayerExtended issue?

**Comment by protyposis** [comment]
This seems to be an Android issue. I remember running into that before but am not sure what the outcome was. You could try to implement a custom `MediaSource` by copying [FileSource](https://github.com/protyposis/MediaPlayer-Extended/blob/master/MediaPlayer/src/main/java/net/protyposis/android/mediaplayer/FileSource.java) and providing the `MediaExtractor` a `FileDescriptor` as [described here](https://stackoverflow.com/a/45542421/370252) instead of the file path.

**Comment by velocitysystems** [comment]
@protyposis Thanks Mario.

I tried what you suggested but it seems even with a custom FileSource implementing IMediaSource and providing the MediaExtractor with a FileDescriptor, we still received the same error.

We've only got a Samsung 4.1 device in our lab, so going to track down another non-Samsung device and see if the same issue occurs. Thanks!

**Comment by protyposis** [comment]
Android 4.1.1 is extremely rare afaik and most 4.1 devices run 4.1.2, on which this issue does not happen, at least not on various Samsung Galaxy phones I tested. 

I also remember a case where opening a local file did not work, whereas streaming it over HTTP did, and a local proxy server was used to serve the local file. That's probably too much effort to implement for such a rare device and I don't know if it applies here, but you could at least test if that's the case here by just opening the file from a remote server.

Not really a solution but at least an option: there's an Android 4.2 update for this device, so you could check the model and ask the users to update the system.

**Comment by velocitysystems** [comment]
@protyposis Yes, the device we tested on was a Samsung 4.1.1 tablet.
Given this is likely such a rare device these days, we will likely go down the path of prompting them to check to see if a update is available and giving them a message "Cannot play video. Your device needs an update" or similiar.

Thanks for the extra information about HTTP streaming though. That's interesting!
