### ISSUE TITLE
stop media player when seeking

### ISSUE THREAD

**Issue by jasonross** [protyposis/ITEC-MediaPlayer#83]
If I am seeking a youtube video and stop it, it is stuck.

seeking a youtube video may need 3 seconds, releaseInternal is scheduled after seekInternal, so we need wait 3 seconds in main thread which is not a good user experience.

Can we fix this issue?  Thanks a lot!

**Comment by protyposis** [comment]
If you don't need frame-exact seeking, you could try `setSeekMode(SeekMode.FAST_TO_CLOSEST_SYNC)`. That should be faster. 

Else, you'll have to please provide me a link to a video where this issue happens so I can take a look if it can be fixed.
