### ISSUE TITLE
how can segmentDownload into file and playback

### ISSUE THREAD

**Issue by lincentma** [protyposis/ITEC-MediaPlayer#85]
Hello, I have a question for the mediaplayer-dash that I don't know how to implement. 
How can download the selected segment into the dir in scard? 
and playback the downloaded segment?
Because I want download these segments to share with other clients to.

I'm a new Android programmer.Thank you.

**Comment by protyposis** [comment]
This would require a major refactoring in the library. The download cache size is hardcoded in `DashMediaExtractor#mUsedCacheSize` to 100MB and you could increase that to cover the whole stream. The directory where the files are stored to can be customized in `DashMediaExtractor#getTempFile`. This would however only download all segments if you playback the video.

To download the segments without playback, you'd have to extract the downloading logic from `DashMediaExtractor` into a separate class that downloads all segments. And then you'd also have to rewrite the DASH manifest to point to the local segments. 

Not a trivial task.

**Comment by lincentma** [comment]
Thank you very much for your advice.
My current idea is to store the contents of the response with okHTTP to scard after request.
Then before request the segment, check the segment whether or not exists in the directory
May I ask you about the idea of implementing to use webrtc to receive the segment data instead of okHttp when other client has the segment data?

**Comment by protyposis** [comment]
It's surely possible to retrieve segments over other protocols than HTTP (e.g. WebRTC, P2P) by replacing the default `SegmentDownloader`.
