### ISSUE TITLE
Multiple LAGGING

### ISSUE THREAD

**Issue by andreabonassi** [protyposis/ITEC-MediaPlayer#87]
Good morning, When I play a video the log continually shows me these messages:
01-08 12:26:08.456 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.489 D/MediaPlayer( 6869): LAGGING -320213812
01-08 12:26:08.489 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.513 D/MediaPlayer( 6869): LAGGING -320197855
01-08 12:26:08.513 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.523 D/MediaPlayer( 6869): LAGGING -320168493
01-08 12:26:08.524 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.535 D/MediaPlayer( 6869): LAGGING -320140133
01-08 12:26:08.536 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.622 D/MediaPlayer( 6869): LAGGING -320187223
01-08 12:26:08.622 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.632 D/MediaPlayer( 6869): LAGGING -320156994
01-08 12:26:08.632 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.642 D/MediaPlayer( 6869): LAGGING -320127039
01-08 12:26:08.642 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.654 D/MediaPlayer( 6869): LAGGING -320099393
01-08 12:26:08.655 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.709 D/MediaPlayer( 6869): LAGGING -320114381
01-08 12:26:08.710 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.733 D/MediaPlayer( 6869): LAGGING -320098350
01-08 12:26:08.734 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.744 D/MediaPlayer( 6869): LAGGING -320068939
01-08 12:26:08.744 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.767 D/MediaPlayer( 6869): LAGGING -320051824
01-08 12:26:08.767 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.822 D/MediaPlayer( 6869): LAGGING -320066793
01-08 12:26:08.822 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.846 D/MediaPlayer( 6869): LAGGING -320050802
01-08 12:26:08.846 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.856 D/MediaPlayer( 6869): LAGGING -320021348
01-08 12:26:08.856 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.869 D/MediaPlayer( 6869): LAGGING -319993881
01-08 12:26:08.869 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.959 D/MediaPlayer( 6869): LAGGING -320043754
01-08 12:26:08.959 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.969 D/MediaPlayer( 6869): LAGGING -320013833
01-08 12:26:08.969 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.979 D/MediaPlayer( 6869): LAGGING -319983713
01-08 12:26:08.979 D/MediaPlayer( 6869): onInfo
01-08 12:26:08.989 D/MediaPlayer( 6869): LAGGING -319954552

What does it mean?

**Comment by protyposis** [comment]
It meas there's something wrong with the timestamps in the video or with their interpretation by the player. Can you provide a sample video file where this happens?

**Comment by andreabonassi** [comment]
I attacched a sample video, all of my videos are encoded in this way.

[sample_video.zip](https://github.com/protyposis/MediaPlayer-Extended/files/1638142/sample_video.zip)

**Comment by andreabonassi** [comment]
any update?

**Comment by protyposis** [comment]
I don't mean to be rude but if there were an update you could read it here ;) If it's urgent you can always contact me for paid priority support.

**Comment by protyposis** [comment]
I tried your sample video but cannot reproduce the issue with v4.3.3. Are you using the latest version? Did it also happen with 4.3.2?

**Comment by andreabonassi** [comment]
I'm also using the latest version, the only difference we might have is that I'm developing on an embedded board (quadcore, 1 gb ram).
Also happened with the previous version.
I certainly did not have the power of a phone.

**Comment by protyposis** [comment]
I guess it has enough power to render a simple video. The log message actually means that the video frames are rendered ~320 seconds too late. Even on a really slow hardware platform that is a little bit too much for a ~10 seconds video. We'd have to find out where the 320 second delay comes from.
