### ISSUE TITLE
Unable to compile, Gardle related endless errors. Please fix them

### ISSUE THREAD

**Issue by pavangayakwad** [protyposis/ITEC-MediaPlayer#89]
I am a newbie and when i download the source and tried to compile in Android Studio 3.0.1, the problems seem endless.

Please find the screenshot.

![1](https://user-images.githubusercontent.com/1834890/35480125-efae8930-042d-11e8-8243-b63afc51a2f9.PNG)
![2](https://user-images.githubusercontent.com/1834890/35480127-efe54592-042d-11e8-92c7-47aadcd43aa5.PNG)

Please help.

**Comment by protyposis** [comment]
You and ignore these errors and safely answer "yes" when asked if you would like the modules to be removed. The errors happen because the repository does not contain the `.iml` files (which are not required as Android Studio can open Gradle projects as well). Building/compiling still works despite these errors.

**Comment by pavangayakwad** [comment]
Ok, I was able to compile the project after choosing "Yes" for the `.iml` warnings. However, the demo projects seems missing. How to get them running?

![3](https://user-images.githubusercontent.com/1834890/35485388-166acd66-0485-11e8-8030-a1664a5e78c2.PNG)

**Comment by protyposis** [comment]
I don't know what exactly you're doing so I can't tell you what's going wrong. What I can tell you is that there definitely is a way, because I just did a fresh checkout, opened it in Android Studio 3.0.1 and was able to build and run the demo app without problems.

**Comment by pavangayakwad** [comment]
Okay, Looks like the problem is when you upgrade Gardle to 4.1. This time, I re-opened source in Android Studio 3.0.1 and chose not to update Gardle to 4.1 and everything worked just fine.

Thank you for your time and assistance @protyposis
