### ISSUE TITLE
Seek fail.

### ISSUE THREAD

**Issue by adawset** [protyposis/ITEC-MediaPlayer#9]
When I seek to the end of video, it's failed.
And can't seek again to any position.

**Comment by protyposis** [comment]
Can you please describe this issue in more detail so I can reproduce it? What is your data source, which type of file/stream are you playing back? Does it happen in the demo app, or are you using the library in your own app? If in your own app, are you using VideoView, GLVideoView, or the MediaPlayer with a custom view?

**Comment by adawset** [comment]
Hi protyposis:
I using a mp4 file recorded by ffmpeg,(H264 & AAC)
It happened in my own app with the MediaPlayer, and I have test it in the demo app, it also happened.
Please download the mp4 from this link: http://pan.baidu.com/s/1hqk273Y
Thanks a lot !

**Comment by protyposis** [comment]
This problem is fixed in the newest version 1.4.3. Thanks for reporting!
