### ISSUE TITLE
Video rotation not correct in pre-lollipop

### ISSUE THREAD

**Issue by kuoliangkwong** [protyposis/ITEC-MediaPlayer#90]
I'm testing on ASUS Zenphone T00J Android version 4.4.2. It displays incorrect video orientation as depicted below:

 Incorrect:
![device-2018-01-30-163816](https://user-images.githubusercontent.com/8188634/35556128-6349ae4c-05dc-11e8-8b70-77ef8c7d32bb.png)

Correct:
![device-2018-01-30-164020](https://user-images.githubusercontent.com/8188634/35556133-67ff81dc-05dc-11e8-962a-0437345b0247.png)

However, it works correctly on Samsung S4 Android 5.0.

**Comment by protyposis** [comment]
Video rotation is unfortunately not supported in Android <= 4.x, see #54.
